<?xml version="1.0" encoding="iso-8859-2"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!DOCTYPE INSTYTUT [
<!ELEMENT INSTYTUT (ZESPOLY)>
<!ATTLIST INSTYTUT NAZWA CDATA #REQUIRED ULICA CDATA #IMPLIED
KOD CDATA #IMPLIED MIASTO CDATA #FIXED "POZNAN">
<!ELEMENT ZESPOLY (ZESPOL)+>
<!ELEMENT ZESPOL (NAZWA,PRACOWNICY?)>
<!ELEMENT NAZWA (#PCDATA)>
<!ELEMENT PRACOWNICY (PRACOWNIK)+>
<!ELEMENT PRACOWNIK (NAZWISKO,ETAT,PLACA)>
<!ATTLIST PRACOWNIK ID_PRAC ID #REQUIRED>
<!ELEMENT NAZWISKO (#PCDATA)>
<!ELEMENT ETAT (#PCDATA)>
<!ELEMENT PLACA (#PCDATA)>
<!ENTITY szef "DYREKTOR">
]>
<INSTYTUT NAZWA="INSTYTUT INFORMATYKI" ULICA="PIOTROWO 2" KOD="60-965" MIASTO="POZNAN">
	<ZESPOLY>
		<ZESPOL>
			<NAZWA>ADMINISTRACJA</NAZWA>
			<PRACOWNICY>
				<PRACOWNIK ID_PRAC="p180">
					<NAZWISKO>MAREK</NAZWISKO><ETAT>SEKRETARKA</ETAT><PLACA>410,2</PLACA>
				</PRACOWNIK>
				<PRACOWNIK ID_PRAC="p100">
					<NAZWISKO>WEGLARZ</NAZWISKO>
					<ETAT>&szef;</ETAT>
					<PLACA>1730</PLACA>
				</PRACOWNIK>
			</PRACOWNICY>
		</ZESPOL>
		<ZESPOL>
			<NAZWA>ALGORYTMY</NAZWA>
			<PRACOWNICY>
				<PRACOWNIK ID_PRAC="p110">
					<NAZWISKO>BLAZEWICZ</NAZWISKO><ETAT>PROFESOR</ETAT><PLACA>1350</PLACA>
				</PRACOWNIK>
			</PRACOWNICY>
		</ZESPOL>
		<ZESPOL>
			<NAZWA>SYSTEMY EKSPERCKIE</NAZWA>
			<PRACOWNICY>
				<PRACOWNIK ID_PRAC="p230">
					<NAZWISKO>HAPKE</NAZWISKO><ETAT>ASYSTENT</ETAT><PLACA>480</PLACA>
				</PRACOWNIK>
				<PRACOWNIK ID_PRAC="p200">
					<NAZWISKO>ZAKRZEWICZ</NAZWISKO><ETAT>STAZYSTA</ETAT><PLACA>208</PLACA>
				</PRACOWNIK>
			</PRACOWNICY>
		</ZESPOL>
		<ZESPOL>
			<NAZWA>SYSTEMY ROZPROSZONE</NAZWA>
			<PRACOWNICY>
				<PRACOWNIK ID_PRAC="p220">
					<NAZWISKO>KONOPKA</NAZWISKO><ETAT>ASYSTENT</ETAT><PLACA>480</PLACA>
				</PRACOWNIK>
				<PRACOWNIK ID_PRAC="p190">
					<NAZWISKO>MATYSIAK</NAZWISKO><ETAT>ASYSTENT</ETAT><PLACA>371</PLACA>
				</PRACOWNIK>
				<PRACOWNIK ID_PRAC="p170">
					<NAZWISKO>JEZIERSKI</NAZWISKO><ETAT>ASYSTENT</ETAT><PLACA>439,7</PLACA>
				</PRACOWNIK>
				<PRACOWNIK ID_PRAC="p160">
					<NAZWISKO>KOSZLAJDA</NAZWISKO><ETAT>ADIUNKT</ETAT><PLACA>590</PLACA>
				</PRACOWNIK>
			</PRACOWNICY>
		</ZESPOL>
		<ZESPOL>
			<NAZWA>BADANIA OPERACYJNE</NAZWA>
		</ZESPOL>
	</ZESPOLY>
</INSTYTUT>