=== majesiu/AI/xml/zespoly.xsd
<?xml version="1.0" encoding="iso-8859-2"?>
<xs:schema targetNamespace="www.cs.put.poznan.pl"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns="www.cs.put.poznan.pl" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ZESPOLY">
		<xs:annotation>
			<xs:documentation>
				Zbior zespolow skladajacych sie na Instytut Informatyki
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ZESPOL" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NAZWA" type="xs:string"/>
							<xs:element name="ADRES" type="xs:string"/>
							<xs:element name="EMAIL">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[a-zA-Z\.]+@([a-zA-Z0-9]+\.)+[a-zA-Z]{2,6}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ID" type="xs:integer" use="required"/>
						<xs:attribute name="CZY_PRACOWNICY" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="DATA_RAPORTU" type="xs:date"/>
				<xs:element name="FORMAT_RAPORTU">
					<xs:simpleType> 
						<xs:restriction base="xs:string">
							<xs:enumeration value="txt"/>
							<xs:enumeration value="html"/>
							<xs:enumeration value="pdf"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== majesiu/AI/xml/zespoly.xml
<?xml version="1.0" encoding="iso-8859-2"?>
<ZESPOLY xmlns="www.cs.put.poznan.pl"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.cs.put.poznan.pl zespoly.xsd">
	<ZESPOL ID="10">
		<NAZWA>ADMINISTRACJA</NAZWA><ADRES>PIOTROWO 3A</ADRES>
		<EMAIL>admin@cs.put.poznan.pl</EMAIL>
	</ZESPOL>
	<ZESPOL ID="20">
		<NAZWA>SYSTEMY ROZPROSZONE</NAZWA><ADRES>PIOTROWO 3A</ADRES>
		<EMAIL>systemy.rozproszone@cs.put.poznan.pl</EMAIL>
	</ZESPOL>
	<ZESPOL ID="30">
		<NAZWA>SYSTEMY EKSPERCKIE</NAZWA><ADRES>STRZELECKA 14</ADRES>
		<EMAIL>systemy.eksperckie@cs.put.poznan.pl</EMAIL>
	</ZESPOL>
	<ZESPOL ID="40">
		<NAZWA>ALGORYTMY</NAZWA><ADRES>WLODKOWICA 16</ADRES>
		<EMAIL>algo@cs.put.poznan.pl</EMAIL>
	</ZESPOL>
	<ZESPOL ID="50" CZY_PRACOWNICY="false">
		<NAZWA>BADANIA OPERACYJNE</NAZWA><ADRES>MIELZYNSKIEGO 30</ADRES>
		<EMAIL>b.o@cs.put.poznan.pl</EMAIL>
	</ZESPOL>
	<DATA_RAPORTU>2010-01-31</DATA_RAPORTU>
	<FORMAT_RAPORTU>pdf</FORMAT_RAPORTU>
</ZESPOLY>
